url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "renatmannanov.github.io" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

collections:
  posts:
    output: true
    permalink: /blog/:title