url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "http://127.0.0.1:4000//" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# permalink: pretty

collections:
  posts:
    output: true
    permalink: /blog/:title

sass:
    sass_dir: _sass
    style: compressed